cc_library(
    name = "structures_library",
    srcs = [
    ],
    hdrs = [
        "hash_map.hpp",
        "heap.hpp",
        "lru_cache.hpp",
    ],
    visibility = [
        "//visibility:public",
    ],
)