cc_test(
  name = "sorting_tests",
  size = "small",
  srcs = [
      "sorting_tests.cpp",
  ],
  deps = [
    "@gtest//:gtest",
    "//algorithms:algorithms_library",
  ],
)

cc_test(
  name = "hashmap_tests",
  size = "small",
  srcs = [
      "hashmap_tests.cpp",
  ],
  deps = [
    "@gtest//:gtest",
    "//structures:structures_library",
  ],
)