cc_library(
    name = "algorithms_library",
    srcs = [
        "utils.cpp",
        "graphsearch.cpp",
    ],
    hdrs = [
        "utils.hpp",
        "mergesort.hpp",
        "quicksort.hpp",
        "graphsearch.hpp",
    ],
    visibility = [
        "//visibility:public",
    ],
)