cc_binary(
    name = "array_to_tree",
    srcs = [
        "sorted_array_to_tree.cpp",
        "tree_utils.hpp",
        "tree_utils.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "tree_from_preorder",
    srcs = [
        "btree_from_preorder.cpp",
        "tree_utils.hpp",
        "tree_utils.cpp",
    ],
    visibility = ["//visibility:public"],
)
