cc_binary(
    name = "array_to_tree",
    srcs = [
        "sorted_array_to_tree.cpp",
        "tree_utils.hpp",
        "tree_utils.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "tree_from_preorder",
    srcs = [
        "btree_from_preorder.cpp",
        "tree_utils.hpp",
        "tree_utils.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "min_ops_ro_reduce_x",
    srcs = [
        "min_ops_ro_reduce_x_to_zero.cpp",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "print_in_order",
    srcs = [
        "print_in_order.cpp",
    ],
    visibility = ["//visibility:public"],
    linkopts = [
        "-lpthread",
    ],
)

cc_binary(
    name = "print_foobar",
    srcs = [
        "print_foobar.cpp",
    ],
    visibility = ["//visibility:public"],
    linkopts = [
        "-lpthread",
    ],
)

cc_binary(
    name = "h2o_builder",
    srcs = [
        "h2o_builder.cpp",
    ],
    visibility = ["//visibility:public"],
    linkopts = [
        "-lpthread",
    ],
)

cc_binary(
    name = "print_zero_even_odd",
    srcs = [
        "print_zero_even_odd.cpp",
    ],
    visibility = ["//visibility:public"],
    linkopts = [
        "-lpthread",
    ],
)

cc_binary(
    name = "3sum",
    srcs = [
        "3sum.cpp",
    ],
    visibility = ["//visibility:public"],
)
