cc_binary(
    name = "mergesort_demo",
    srcs = [
        "sorting_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//algorithms:algorithms_library",
    ],
    visibility = ["//visibility:public"],
)
