cc_binary(
    name = "mergesort_demo",
    srcs = [
        "sorting_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//algorithms:algorithms_library",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "hashmap_demo",
    srcs = [
        "hashmap_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//structures:structures_library",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "graphsearch_demo",
    srcs = [
        "graphsearch_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//algorithms:algorithms_library",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "dijkstra_demo",
    srcs = [
        "dijkstra_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//algorithms:algorithms_library",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "heap_demo",
    srcs = [
        "heap_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//structures:structures_library",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "lru_cache_demo",
    srcs = [
        "lru_cache_demo.cpp",
        "prettyprint.hpp",
    ],
    deps = [
        "//structures:structures_library",
    ],
    visibility = ["//visibility:public"],
)
